### ISSUE TITLE
`TopicSet` and `Topic` should not depend on `Task`

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#23]
At least for TREC-PM, topics are the same for both tasks.

Indeed, `task` seems to be used only for ids and hashes, conversely used only for a `GoldStandard`, this dependent on a task.

**Comment by khituras** [comment]
I prefer to conceptually assume that the equality between the topics for the `BioMedLiteratur` and `ClinicalTrials` task is basically a coincidence. Because otherwise, one would need to model that one `TopicSet` might be applied to multiple tasks which seems unnecessarily complicated to me.

Technically, the task is required to derive the index name in the `ElasticSearchQuery`:

	  @Override
	    public List<Result> query(T topic) {
	        ElasticSearch es;
	        final String index = this.index != null ? this.index : Retrieval.getIndexName(topic.getTask());
	        if (this.types != null) {
	            es = new ElasticSearch(index, parameters, this.types);
	        } else {
	            es = new ElasticSearch(index, parameters);
	        }
	        return es.query(new JSONObject(jsonQuery));
	    }
which in turn makes use of

	    public static String getIndexName(Task task) {
	        switch (task) {
	            case CLINICAL_TRIALS:
	                return TrecConfig.ELASTIC_CT_INDEX;
	            case PUBMED:
	                return TrecConfig.ELASTIC_BA_INDEX;
	            default:
	                return "";
	        }
	    }
We could, of course, determine the index in some other way. But for now, I don't see why we should bother. Also for the future I do not expect the number of supported tasks to grow in a way that the current approach wouldn't be feasible any more

**Comment by michelole** [comment]
From my side what bothers is that every time I need to create an `AtomicGoldStandard` I have to pass the task to both the GS and the `TopicSet` *which is required* by the GS itself. I ended up passing null to the `TopicSet` just to be able to reuse the object for different tasks in a "safe" way.

Coming back to your reasoning, what was originally intent to wrap the `TopicSet` and give it an index (thus preparing it for a search) was indeed the query decorator pattern, which "decorates" a topic for a search. This was explicitly set by the `ElasticSearchQuery(String index, String... types)` constructor, which seems to not be used any longer given the check for null in the code you posted.

Interestingly enough, the new constructor receives a `GoldStandard` enum. If #16 were implemented, then the task could be provided by this object. This makes more sense to me, what do you think?

**Comment by khituras** [comment]
Reason why the index isn't passed any more through the `ElasticSearchQuery(String index, String... types)` constructor: I wanted - or did - decouple the actual retrieval part from the old `Experiments` class. But the `Experiments` object passed the index.

Actually, it can't really stay as it is now because for LtR I will have to query multiple indices. So I would welcome a more elegant way to specify the index. However, I did not understand wich object you meant which "the task could be provided by this object" in the last paragraph in your comment above.

**Comment by michelole** [comment]
I noticed first hand today the advantage of decoupling `Experiment` and `Retrieval`: no need to set a GS (and thus calculate metrics) if you're just performing a query to get results. Thanks!

However, I don't see why `Retrieval` could not pass the index, since it knows the task.

> However, I did not understand wich object you meant which "the task could be provided by this object" in the last paragraph in your comment above.
I meant any object that extends `GoldStandard`, e.g. `TrecQrelGoldStandard`. HOWEVER, I now think that `Retrieval` should not depend on the gold standard at all, because it's meant to be independent.

I don't get why LtR requires multiple indices, but maybe we could discuss that on Slack.

**Comment by khituras** [comment]
> However, I don't see why Retrieval could not pass the index, since it knows the task.

I think I remember to problem now: If you pass the index to the constructor of the ElasticSearchQuery, you cannot use the same Retrieval object to search on another index. This is why I wanted something more dynamic. We can gladly have the Retrieval determine the index - I even think that would be the place where it should go. I guess I just did not come across that point again and it worked so far how it is now.

> I don't get why LtR requires multiple indices, but maybe we could discuss that on Slack.

That’s actually not that complicated: For LtR, a common feature are traditional document retrieval scores, bm25, DFR, LM etc (just check out the Lucene/ElasticSearch similarities). I know no other way than to create multiple indices in order to obtain those metrics for a specific document ID.

**Comment by michelole** [comment]
Another problem of making `Retrieval` agnostic is that it currently encapsulates (and builds!) the `Query` object (i.e. the query decorator pattern), which was not designed to be agnostic.

Coming back to your need to have multiple indices in LtR, AFAIK similarity can be set on ES per field. See https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html.

In 2017 we used it to try at least one BM25 variation (b=0, see https://github.com/bst-mug/trec-2017-precision-medicine/blob/master/src/main/resources/templates/b0.json).

**Comment by khituras** [comment]
The similarity per field thing is true. But it would be much more complicated to vary the fields because it would require a different mapping and actually different documents (with the fields duplicated) to the index. I would very much prefer the current approach where I can send the exact same document to an index with a rather uniform mapping.

Also, `Retrieval` was particularly meant as an isolated way to build the `Query`, so this is alright in my mind.

What exactly is the issue here with `Retrieval`? :-D

**Comment by michelole** [comment]
Got your point about different indices. That means that now index = f(task,metric). How do you plan to accommodate for that? What if you used a different [type](https://www.elastic.co/blog/index-vs-type)?

But I agree that we digressed. My main motivation is to better understand the class model so that new code uses it accordingly and we progressively remove/deprecate old code. So far I've seen `Experiment` = `Retrieval` + `GoldStandard`, which makes sense for me. But so far some things are reusable, some not (e.g. `Retrieval` and the inner task variable). Even worse, some stuff is reusable in some code paths and not in others (e.g. `ElasticSearchQuery.query`).

**Comment by khituras** [comment]
There are [no types any more](https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html). Also, I think `index = f(task,metric,year)`, isn't it? This is why all three parameters are around everywhere.

Concerning the class model: Actually, the current state is more of a refactoring of the old state. I needed some functionality to work on its own while not crippling existing experiments.

To be honest, I haven't thought further than that for now. The current state is certainly not ideal but it is working for me and can produce results which we need soon.

That being said I'm of course interested in transitioning into a better class model that is clearer, less error prone and more self-explanatory.

**Comment by michelole** [comment]
Experiment => Evaluation
Experiment = Retrieval + GoldStandard + TopicSet + StatsWriter

**Comment by michelole** [comment]
Over Skype we decided that `Retrieval` will not be reused and receive an index instead of {task,metric,year}
