### ISSUE TITLE
`AtomicGoldStandard` should encapsulate a single file

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#24]
Both clinical trials in 2017 and internal gold standards don't have a sample qrels file.

Instead of accepting and handling nulls in the `AtomicGoldStandard` class, make it hold a single resource and, if necessary, use `AggregatedGoldStandard` to aggregate the traditional and sample qrels files. (However, this should not be necessary in TREC-PM, as the sample qrels should be a superset of the traditional qrels).

This is a follow-up of https://github.com/JULIELab/trec-pm/pull/20#issuecomment-510371220.

**Comment by khituras** [comment]
I'm not sure that it would be better to introduce the `AggregatedGoldStandard` for this issue instead for the null check. Especially since you are theoretically right and the sample qrels *could* be a superset of traditional qrels, but:

    ➜  gold-standard git:(master) ✗ cut -d" " -f4 qrels-treceval-abstracts.2018.txt | sort | uniq -c
    16841 0
    2146 1
    3442 2
    ➜  gold-standard git:(master) ✗ cut -d" " -f5 qrels-sample-abstracts.2018.txt| sort | uniq -c
    43477 -1
    16876 0
    2117 1
    3436 2
    ➜  gold-standard git:(master) ✗

I have no idea why but the label distribution  - apart from the 'not sampled' -1 label - slightly differs. While it perhaps shouldn't, it still does. So I would prefer keeping the original files to keep the evaluation score comparison intact.

To avoid the `null` check one could just return a default empty file in a [temporary directory](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/File.html#createTempFile(java.lang.String,java.lang.String)) so one would always obtain an infNDCG score but it would be 0 if there is no sample file.

**Comment by michelole** [comment]
I dug up on this inconsistency and actually found a bug, which I will address separately on #27. We can assume here the files *are consistent* and re-consider using only the sample files for metric calculations.

**Comment by michelole** [comment]
There's one reason to still use traditional .qrels file though, as traditional metrics (such as P10) might differ when using trec_eval or sample_eval. My approach would be, however, to load the full data using the sample files and dump the data into the two different formats using `writeQrelFile`. We could write tests to ensure the written qrels are exactly the same as the ones provided.

**Comment by khituras** [comment]
But wasn't the whole idea to get rid of two files? This sounds rather complicated to me but perhaps I didn't really understand the plan :-)

**Comment by michelole** [comment]
Over Skype we decided to receive only a single `File` as constructor and use, wherever possible, the sample qrels file.

If needed (e.g. CT in 2017), we can decide at run-time if sample is available by checking the first doc in the `DocumentList` if stratum is defined.
